# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField(default=0)),
                ('group_open', models.BooleanField(default=True)),
                ('group_size', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='FContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.IntegerField(default=0)),
                ('content_type', models.IntegerField(default=0)),
                ('content_title', models.CharField(blank=True, max_length=250, null=True)),
                ('content_link', models.CharField(blank=True, max_length=250, null=True)),
                ('content_youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('content_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('content_filename', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('teacher_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('teacher_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
