# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_fclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcontent',
            old_name='content_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='fcontent',
            old_name='content_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='fcontent',
            old_name='content_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='fcontent',
            old_name='content_type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='fcontent',
            old_name='content_youtube',
            new_name='youtube',
        ),
        migrations.AddField(
            model_name='fcontent',
            name='memo',
            field=models.TextField(default=b''),
        ),
    ]
