# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-25 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20170624_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcontent',
            old_name='content_filename',
            new_name='filename',
        ),
    ]
