# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20170702_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='fwork',
            name='domains',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='fwork',
            name='levels',
            field=models.TextField(default=b''),
        ),
    ]
