# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20170702_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fwork',
            name='title',
            field=models.CharField(max_length=250, verbose_name=b'\xe8\xa8\x8e\xe8\xab\x96\xe4\xb8\xbb\xe9\xa1\x8c'),
        ),
    ]
