# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-07 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_fclass_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fclass',
            name='deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
