# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20170811_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speculationclass',
            old_name='speculation_id',
            new_name='forum_id',
        ),
        migrations.RenameField(
            model_name='speculationcontent',
            old_name='speculation_id',
            new_name='forum_id',
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
