# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-11 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20170811_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeculationAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.IntegerField(default=0)),
                ('kind', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
