# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_auto_20170824_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='fcontent',
            name='filename',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='speculationcontent',
            name='filename',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
