# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-14 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_auto_20171014_0930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ClassroomGroup',
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
