# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-14 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0032_auto_20171014_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomgroup',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='classroomgroup',
            name='numbers',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
