# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-14 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0037_auto_20171014_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomgroup',
            old_name='open',
            new_name='opening',
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
