# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0045_auto_20171025_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=b'\xe6\xb8\xac\xe9\xa9\x97\xe4\xb8\xbb\xe9\xa1\x8c')),
                ('user_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('domains', models.TextField(default=b'')),
                ('levels', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ExamClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.BooleanField(default=False)),
                ('deadline_date', models.DateTimeField(default=teacher.models.get_deadline)),
            ],
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
