# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-27 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0057_auto_20171027_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='examclass',
            name='round_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
