# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-07 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0059_auto_20171104_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.BooleanField(default=False)),
                ('deadline_date', models.DateTimeField(default=teacher.models.get_deadline)),
            ],
        ),
        migrations.CreateModel(
            name='TeamContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('memo', models.TextField(default=b'')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('filename', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=b'\xe4\xbb\xbb\xe5\x8b\x99\xe4\xb8\xbb\xe9\xa1\x8c')),
                ('teacher_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('domains', models.TextField(default=b'')),
                ('levels', models.TextField(default=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='examclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='speculationclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterUniqueTogether(
            name='examclass',
            unique_together=set([('exam_id', 'classroom_id')]),
        ),
    ]
