# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0060_auto_20171107_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamclass',
            old_name='forum_id',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='teamcontent',
            old_name='forum_id',
            new_name='team_id',
        ),
        migrations.AlterField(
            model_name='examclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='speculationclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
