# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0062_auto_20171111_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcontent',
            name='youtube_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='speculationclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
