# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0064_auto_20171112_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='speculationclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
