# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0065_auto_20180923_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.BooleanField(default=False)),
                ('deadline_date', models.DateTimeField(default=teacher.models.get_deadline)),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('memo', models.TextField(default=b'')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube_length', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('filename', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=b'\xe8\xaa\xb2\xe7\xa8\x8b\xe4\xb8\xbb\xe9\xa1\x8c')),
                ('teacher_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('domains', models.TextField(default=b'')),
                ('levels', models.TextField(default=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='examclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='fclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='speculationclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='teamclass',
            name='deadline_date',
            field=models.DateTimeField(default=teacher.models.get_deadline),
        ),
    ]
