# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0068_auto_20190207_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='answer',
            new_name='answer_select',
        ),
        migrations.RenameField(
            model_name='examquestion',
            old_name='answer_assay',
            new_name='answer_short',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='answer_tf',
            field=models.BooleanField(default=0),
        ),
    ]
