# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0069_auto_20190207_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='filename',
            new_name='title_filename',
        ),
        migrations.RenameField(
            model_name='examquestion',
            old_name='pic',
            new_name='title_pic',
        ),
    ]
