# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0070_auto_20190207_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamImportQuestion1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'')),
                ('answer_tf', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamImportQuestion3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'')),
                ('answer_filling', models.TextField(default=b'')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='examimportquestion2',
            old_name='answer',
            new_name='answer_select',
        ),
    ]
