# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0071_auto_20190207_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExcise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_content_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('excise_id', models.IntegerField(default=0)),
            ],
        ),
    ]
