# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0075_auto_20190207_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 8, 47, 53, 981000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='speculationwork',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 8, 47, 53, 978000, tzinfo=utc)),
        ),
    ]
