# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0076_auto_20190207_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 8, 51, 49, 232000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='speculationwork',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 8, 51, 49, 229000, tzinfo=utc)),
        ),
    ]
