# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0077_auto_20190207_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='speculationwork',
            name='publication_date',
        ),
    ]
