# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0078_auto_20190208_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='answer_short',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='answer_filling',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='answer_select',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='answer_tf',
        ),
    ]
