# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0079_auto_20190208_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examimportquestion1',
            old_name='answer_tf',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='examimportquestion2',
            old_name='answer_select',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='examimportquestion3',
            old_name='answer_filling',
            new_name='answer',
        ),
    ]
