# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0081_auto_20190208_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='opening',
            field=models.BooleanField(default=False),
        ),
    ]
