# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reply',
            field=models.FloatField(default=0.0),
        ),
    ]
