# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170702_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='classroom_id',
            field=models.IntegerField(default=0),
        ),
    ]
