# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-02 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170702_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(default=b'', max_length=200, verbose_name=b'\xe9\xa0\x98\xe5\x9f\x9f\xe5\x90\x8d\xe7\xa8\xb1'),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(default=b'', max_length=200, verbose_name=b'\xe5\xb9\xb4\xe7\xb4\x9a'),
        ),
    ]
