# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170702_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_count', models.IntegerField(default=0)),
                ('visitor_count', models.IntegerField(default=0)),
                ('open_time', models.DateTimeField(auto_now_add=True)),
                ('site_name', models.CharField(max_length=50)),
                ('site_image', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='visitor_count',
        ),
    ]
