# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-05 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170705_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together=set([('student_id', 'parent_id')]),
        ),
    ]
