# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-08 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_messagecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecontent',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
