# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-08 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_message_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_type',
            new_name='type',
        ),
    ]
