# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-08 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170708_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.AddField(
            model_name='messagepoll',
            name='message_type',
            field=models.IntegerField(default=0),
        ),
    ]
