# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_image',
            field=models.CharField(max_length=255),
        ),
    ]
