# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-23 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20170822_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontent',
            name='filename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
