# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20170823_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'', max_length=50)),
                ('first_name', models.CharField(default=b'', max_length=50)),
                ('password', models.CharField(default=b'', max_length=50)),
                ('email', models.CharField(default=b'', max_length=100)),
            ],
        ),
    ]
