# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-11 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_importuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='classroom_id',
            new_name='youtube_id',
        ),
    ]
