# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-08 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='page_path',
        ),
        migrations.AddField(
            model_name='annotation',
            name='findex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='stuid',
            field=models.IntegerField(default=0),
        ),
    ]
