# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models
from teacher.models import SpeculationContent
from annotate.models import Annotation

def set_material_id(apps, schema_editor):
  for annotation in Annotation.objects.filter(ftype=1):
    material = SpeculationContent.objects.get(forum_id=annotation.findex, types=1)
    annotation.mid = material.id
    annotation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_auto_20170814_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='mid',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_material_id),
    ]
