# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-05-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0004_annotation_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation',
            field=models.TextField(default=''),
        ),
    ]
