# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-25 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_sfwork_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfwork',
            old_name='like',
            new_name='likes',
        ),
    ]
