# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-25 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170625_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfwork',
            name='classroom_id',
            field=models.IntegerField(default=0),
        ),
    ]
