# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-25 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_sfwork_classroom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfwork',
            name='classroom_id',
        ),
    ]
