# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_sfwork_classroom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('memo', models.TextField(default=b'')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='sfwork',
            name='reply',
            field=models.IntegerField(default=0),
        ),
    ]
