# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-01 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_sfreply_work_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('filename', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
