# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-01 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_sfcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfcontent',
            name='file',
        ),
        migrations.AddField(
            model_name='sfcontent',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
