# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_sfcontent_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfcontent',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sfcontent',
            name='work_id',
            field=models.IntegerField(default=0),
        ),
    ]
