# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20170701_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfcontent',
            name='delete_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
