# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_sfwork_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfwork',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sfwork',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sfwork',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
