# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-02 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20170702_0439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assistant',
        ),
    ]
