# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_delete_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfwork',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
