# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-11 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_sfwork_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSpeculationWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
                ('memo', models.TextField(default=b'')),
                ('publish', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('scorer', models.IntegerField(default=0)),
                ('likes', models.TextField(default=b'')),
                ('like_count', models.IntegerField(default=0)),
                ('reply', models.IntegerField(default=0)),
            ],
        ),
    ]
