# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_sspeculationwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSpeculationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('work_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('filename', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
