# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_sspeculationcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sspeculationcontent',
            name='filename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
