# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20170824_0602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SWork',
        ),
        migrations.AlterField(
            model_name='sfcontent',
            name='filename',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sspeculationcontent',
            name='filename',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
