# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20170909_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfwork',
            name='memo_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sfwork',
            name='memo_e',
            field=models.IntegerField(default=0),
        ),
    ]
