# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-14 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20171009_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('enroll_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together=set([('enroll_id', 'group_id')]),
        ),
    ]
