# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-25 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_sfwork_commment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfwork',
            name='comment',
            field=models.TextField(default=b''),
        ),
    ]
