# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-25 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_sfwork_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfwork',
            name='commment',
        ),
    ]
