# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-25 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20171025_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfwork',
            name='comment_publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
