# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-26 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_sfwork_comment_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('exam_id', models.IntegerField()),
                ('publish', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('scorer', models.IntegerField(default=0)),
            ],
        ),
    ]
