# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_examwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together=set([('student_id', 'exam_id', 'question_id')]),
        ),
    ]
