# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-27 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20171027_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='exam_id',
            new_name='exam_work_id',
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together=set([('student_id', 'exam_work_id', 'question_id')]),
        ),
    ]
