# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-04 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20171027_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='examwork',
            name='questions',
            field=models.TextField(default=b''),
        ),
    ]
