# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_examwork_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sspeculationwork',
            name='comment',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='sspeculationwork',
            name='comment_publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
