# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_auto_20181027_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=0)),
                ('group_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('memo', models.TextField(default=b'')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube_length', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('filename', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
