# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_teamcontent_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('group', models.IntegerField(default=0)),
                ('enroll_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentgroupleader',
            unique_together=set([('group_id', 'group')]),
        ),
    ]
