# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_auto_20190208_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('course_id', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursecontentprogress',
            unique_together=set([('student_id', 'course_id')]),
        ),
    ]
