# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_auto_20190209_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontentprogress',
            old_name='course_id',
            new_name='content_id',
        ),
        migrations.AlterUniqueTogether(
            name='coursecontentprogress',
            unique_together=set([('student_id', 'content_id')]),
        ),
    ]
