# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_auto_20190209_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontentprogress',
            old_name='end_time',
            new_name='finish_time',
        ),
    ]
