# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-05-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_examanswer_answer_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='examwork',
            name='questions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sfreply',
            name='memo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sfwork',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sfwork',
            name='likes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sfwork',
            name='memo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sspeculationwork',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sspeculationwork',
            name='likes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sspeculationwork',
            name='memo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teamcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teamcontent',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
